### ISSUE TITLE
Initial QField Configuration

### ISSUE THREAD

**Issue by ClaireLush** [jncc/vsas-app-development#34]
Generate QGIS project with 4 layers: survey (tracking), trip, environment and observations.

Configure layers and forms as outlined in:
[New form layout_FOR IDOX.xlsx](https://github.com/jncc/vsas-app-development/files/13265451/New.form.layout_FOR.IDOX.xlsx)

This configuration should consider the 25 user story issues labelled "Must have"

**Comment by ClaireLush** [comment]
@emmawilsonJNCC The ICES binocular vocab (http://vocab.ices.dk/?ref=1719) does not include "Binoculars used for ID only". Does this need adding? If not which of the values from the vocab is the default?

**Comment by Emmawilsonjncc** [comment]
Hi Claire, please could the options within 'use of binoculars' be 'binoculars used for ID only', 'binoculars used for scanning far ahead' and 'binoculars used extensively for scanning ahead and to the side'. These are not the exact same as the ICES options but that's ok - the ICES option of 'no binoculars used' would potentially be confusing for volunteers, hence we have amended this.

**Comment by ClaireLush** [comment]
@Emmawilsonjncc the spreadsheet doesn't include any mention of different fields/LUTs for non-birds. Are these still required?

**Comment by Emmawilsonjncc** [comment]
Non-birds are still required and should be found in the same way that bird species are found i.e. using the observation form, selecting the first drop down for species group and then species from the second drop down. For non-birds, this will look something like drop down 1 = cetaceans, drop down 2 = porpoise. I am currently putting together a list of species groups and species for each drop down and will get this over to you soon!
