### ISSUE TITLE
List of life stages/behaviours/associations for each species/species group

### ISSUE THREAD

**Issue by MikeLush** [jncc/vsas-app-development#45]
Need from Emma.

**Comment by Emmawilsonjncc** [comment]
Provided on other comment but attached again here for ease

[New form layout_FOR IDOX.xlsx](https://github.com/jncc/vsas-app-development/files/13498916/New.form.layout_FOR.IDOX.xlsx)

**Comment by ClaireLush** [comment]
Duplicate of #50
